version: '3'

services:

  mysql-development:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kognita
    ports:
      - "3306:3306"